#!/bin/sh

# Assume variable called STORY_ID of format "#160594666"

read -p "Enter the Story ID, or press enter to use variable STORY_ID: " USER_INPUT_STORY_ID </dev/tty

OUR_STORY_ID=""

if [ ! -z "$USER_INPUT_STORY_ID" ]; then
	OUR_STORY_ID=$USER_INPUT_STORY_ID
else
	OUR_STORY_ID=$STORY_ID
fi

OUR_STORY_ID_WITHOUT_HASH=${OUR_STORY_ID#?}

COMMIT_MSG_FILE=$1

echo "[$OUR_STORY_ID] https://www.pivotaltracker.com/story/show/$OUR_STORY_ID_WITHOUT_HASH\n\n$(cat $COMMIT_MSG_FILE)" > $COMMIT_MSG_FILE